# Site settings
title: Jamie & John's Blog
description: A chronicling of our day to day lives
keywords: Blog, Wedding
author: Jamie
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
